{"uuid": "09423dea-53fc-439c-b080-b358a4ceb949", "children": ["c59fd019-6ecf-4a12-b4a2-31e3c567b749"], "befores": [{"name": "test_LoginToXero", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\mehraj.g\\gitfolder\\python\\xero\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\mehraj.g\\gitfolder\\python\\xero\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\mehraj.g\\gitfolder\\python\\xero\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\mehraj.g\\GitFolder\\Python\\Xero\\Xero_Test\\test_xero.py\", line 92, in test_LoginToXero\n    Reusable_Methods.compare(\"Login | Xero Accounting Software\", driver.title, \"Login Page\")\n  File \"C:\\Users\\mehraj.g\\GitFolder\\Python\\Xero\\Xero_Test\\ReusableMethods.py\", line 15, in compare\n    assert False\n"}, "start": 1603986576400, "stop": 1603986578739}], "start": 1603986576400, "stop": 1603986578748}