{"uuid": "3bbba309-0f8c-4552-b099-fb15ccd6f94e", "children": ["182938df-74eb-4c84-a310-5cc5e89417d5"], "befores": [{"name": "test_LoginToXero", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\mehraj.g\\gitfolder\\python\\xero\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\mehraj.g\\gitfolder\\python\\xero\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\mehraj.g\\gitfolder\\python\\xero\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\mehraj.g\\GitFolder\\Python\\Xero\\Xero_Test\\test_xero.py\", line 92, in test_LoginToXero\n    Reusable_Methods.compare(\"Login | Xero Accounting Software\", driver.title, \"Login Page\")\n  File \"C:\\Users\\mehraj.g\\GitFolder\\Python\\Xero\\Xero_Test\\ReusableMethods.py\", line 15, in compare\n    assert False\n"}, "start": 1603986578750, "stop": 1603986580492}], "start": 1603986578750, "stop": 1603986580501}